apiVersion: v1
kind: ConfigMap
metadata: {name: gitops-web-nginx}
data:
  default.conf: |
    server {
      listen 8080;
      location = /livez { access_log off; return 200 "ok\n"; }
      location = /readyz { access_log off; return 200 "ok\n"; }
      location / { default_type text/plain; return 200 "Argo CD Helm workload\n"; }
    }
