{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata: {name: gitops-web}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector: {matchLabels: {app.kubernetes.io/name: gitops-web}}
{{- end }}
