{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata: {name: {{ default "gitops-web" .Values.serviceAccount.name }}}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
